title: "My Personal Blog"
description: "Thoughts on Math, Movies, and Adventures"
baseurl: "" # Leave blank for GitHub Pages
url: "https://<your-username>.github.io/my-personal-blog"
theme: minima
author: <Hari>
