title: "My Personal Site"
description: "Exploring Maths, Movies, and Adventures."
url: "https://yourusername.github.io"
baseurl: ""

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure
permalink: /:categories/:year/:month/:day/:title/

collections:
  math:
    output: true
  movies:
    output: true
  adventures:
    output: true

markdown: kramdown
highlighter: rouge

# Navigation links
nav_links:
  - name: "Home"
    link: "/"
  - name: "Math"
    link: "/math/"
  - name: "Movies"
    link: "/movies/"
  - name: "Adventures"
    link: "/adventures/"
