title: "My Personal Blog"
description: "Thoughts on Math, Movies, and Adventures"
baseurl: "" # Leave blank for GitHub Pages
url: "https://Hari-13.github.io/my-personal-blog"
theme: minimal
author: Hari
date_format: "%d %m %Y"


# Include posts from subdirectories
collections:
  posts:
    output: true
